# ################################
# Model: avhubert + Linear
# Authors: Xiangming Gu 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
attempt: 1
dur_threshold: 5
overlap: 0
frame_rate: 50
sample_rate: 50
output_folder: !ref results/AVHuBERT/train_video_ssl_dur<dur_threshold>_attempt<attempt>/<seed>
save_folder: !ref <output_folder>/save
csv_folder: !ref data/frame_rate<frame_rate>/dur_<dur_threshold>s
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER # e,g./path/to/DSing
# noise/ris dataset will automatically be downloaded
data_folder_rirs: !ref <data_folder>
ckpt_interval_minutes: 25 # save checkpoint every N min
train_csv: !ref <csv_folder>/n20em_train.csv
valid_csv: !ref <csv_folder>/n20em_valid.csv
test_csv:
   - !ref <csv_folder>/n20em_test.csv
   - !ref <csv_folder>/n20em_valid.csv
   - !ref <csv_folder>/n20em_train.csv

# Training parameters
number_of_epochs: 10
lr: 0.0003
lr_encoder: 0.00005
sorting: ascending
auto_mix_prec: False
linear_prob_epochs: 2

split_noise: False
pretrain: False
pretrain_folder: ../pretrain_model
save_model: False
save_model_folder: ../save_model

# Evaluating parameters
onset_threshold: 0.4
offset_threshold: 0.5
onset_tolerance: 0.05
offset_tolerance: 0.05
pitch_tolerance: 50

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 3 per GPU to fit 32GB of VRAM
batch_size: 8
test_batch_size: 1

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>
   num_workers: 8

valid_dataloader_opts:
   batch_size: !ref <test_batch_size>
   num_workers: 8

test_dataloader_opts:
   batch_size: !ref <test_batch_size>
   num_workers: 8

# Model parameters
freeze_encoder: False

# Outputs
pitch_octave_num: 4
pitch_class_num: 12
feat_dim: 1024
output_neurons: 20  # 2+pitch_octave+pitch_class+2

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

# augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
#    sample_rate: !ref <sample_rate>
#    speeds: [95, 100, 105]

avhubert_url: https://dl.fbaipublicfiles.com/avhubert/model/lrs3_vox/clean-pretrain/large_vox_iter5.pt
encoder: !new:fairseq_interface.FairseqAVHubertPretrain
   pretrained_path: !ref <avhubert_url>
   output_norm: True
   freeze: !ref <freeze_encoder>
   save_path: ssl_model/AVHuBERT/large_vox_iter5.pt

head: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <feat_dim>
   n_neurons: !ref <output_neurons>

modules:
   encoder: !ref <encoder>
   head: !ref <head>

log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True

onset_positive_weight: 15.0
offset_positive_weight: 1.0
onset_criterion: !name:speechbrain.nnet.losses.bce_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

offset_criterion: !name:speechbrain.nnet.losses.bce_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

octave_criterion: !name:speechbrain.nnet.losses.nll_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

pitch_criterion: !name:speechbrain.nnet.losses.nll_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

head_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

encoder_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_encoder>

lr_annealing_head: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_encoder: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_encoder>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0


checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      encoder: !ref <encoder>
      head: !ref <head>
      scheduler_head: !ref <lr_annealing_head>
      scheduler_encoder: !ref <lr_annealing_encoder>
      counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>
   precision: 3

onset_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.bce_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

offset_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.bce_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

octave_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.nll_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

pitch_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.nll_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0