# ################################
# Model: wav2vec2 + Linear
# Authors: Xiangming Gu 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
attempt: 1
dur_threshold: 5
ssl_model: wav2vec2-large-lv60
output_folder: !ref results/<ssl_model>/train_audio_ssl_dur<dur_threshold>_attempt<attempt>/<seed>
save_folder: !ref <output_folder>/save
csv_folder: !ref data/dur_<dur_threshold>s
train_log: !ref <output_folder>/train_log.txt

# URL for the biggest Fairseq english data2vec model.
wav2vec2_hub: !ref facebook/<ssl_model>
wav2vec2_local: !ref ssl_model/<ssl_model>

# Data files
data_folder: !PLACEHOLDER # e,g./path/to/N20EMv2
# noise/ris dataset will automatically be downloaded
data_folder_rirs: !ref <data_folder>
ckpt_interval_minutes: 25 # save checkpoint every N min
train_csv: !ref <csv_folder>/mir_st500_train.csv
valid_csv: !ref <csv_folder>/mir_st500_valid.csv
test_csv:
   - !ref <csv_folder>/mir_st500_test.csv
   - !ref <csv_folder>/tonas.csv
   - !ref <csv_folder>/ismir2014.csv

noise_type: babble
snr_db: -10
add_noise: False
# Training parameters
number_of_epochs: 10
lr: 0.0003
lr_wav2vec: 0.00005
sorting: ascending
auto_mix_prec: False
sample_rate: 16000
frame_rate: 49.8
linear_prob_epochs: 2
pretrain: False
pretrain_folder: ../pretrain_model
save_model: False
save_model_folder: ../save_model

# Evaluating parameters
onset_threshold: 0.4
offset_threshold: 0.5
onset_tolerance: 0.05
pitch_tolerance: 50

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 3 per GPU to fit 32GB of VRAM
batch_size: 8
test_batch_size: 1
num_workers: 8

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>
   num_workers: !ref <num_workers>

valid_dataloader_opts:
   batch_size: !ref <test_batch_size>
   num_workers: !ref <num_workers>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>
   num_workers: !ref <num_workers>

# Model parameters
freeze_wav2vec: False

# Outputs
pitch_octave_num: 4
pitch_class_num: 12
feat_dim: 1024
output_neurons: 20  # 2+pitch_octave+pitch_class+2

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

# augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
#    sample_rate: !ref <sample_rate>
#    speeds: [95, 100, 105]

wav2vec2: !new:huggingface_interface.HuggingFaceWav2Vec2
   source: !ref <wav2vec2_hub>
   output_norm: True
   freeze: !ref <freeze_wav2vec>
   save_path: !ref <wav2vec2_local> # !ref <save_folder>/wav2vec2_checkpoint

#####
# Uncomment this block if you prefer to use a Fairseq pretrained model instead
# of a HuggingFace one. Here, we provide an URL that is obtained from the
# Fairseq github for the multilingual XLSR.
#
# wav2vec2_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/w2v_large_lv_fsh_swbd_cv.pt
# wav2vec2: !new:nets.fairseq_interface.FairseqWav2Vec2
#    pretrained_path: !ref <wav2vec2_url>
#    output_norm: True
#    freeze: False
#    save_path: !ref <wav2vec2_local>

model: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <feat_dim>
   n_neurons: !ref <output_neurons>

modules:
   wav2vec2: !ref <wav2vec2>
   model: !ref <model>

log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True

onset_positive_weight: 15.0
offset_positive_weight: 1.0
onset_criterion: !name:speechbrain.nnet.losses.bce_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

offset_criterion: !name:speechbrain.nnet.losses.bce_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

octave_criterion: !name:speechbrain.nnet.losses.nll_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

pitch_criterion: !name:speechbrain.nnet.losses.nll_loss
   reduction: mean
   allowed_len_diff: 3
   label_smoothing: 0.0

model_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

wav2vec_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_wav2vec>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_wav2vec>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0


checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_folder>
   recoverables:
      wav2vec2: !ref <wav2vec2>
      model: !ref <model>
      scheduler_model: !ref <lr_annealing_model>
      scheduler_wav2vec: !ref <lr_annealing_wav2vec>
      counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>
   precision: 3

onset_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.bce_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

offset_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.bce_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

octave_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.nll_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0

pitch_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.nll_loss
        reduction: batch
        allowed_len_diff: 3
        label_smoothing: 0.0